
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fymvwedfxmhtzamesukr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bXZ3ZWRmeG1odHphbWVzdWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNjY0MjAsImV4cCI6MjA1NDg0MjQyMH0.cpRHdZzSYqoH69OiwIDwl0k-m9gtIpsEZxn0owbTwGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
